services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
